name: mergequick
description: Web application to help developers merge pull requests quick!
version: 0.0.0
homepage: https://github.com/renatoathaydes/mergequick
author: renato <renatoathaydes@hotmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  flattery: ^0.2.0
  dcache: ^0.3.0

dev_dependencies:
  build_runner: ^1.6.7
  build_web_compilers: ^2.2.3
  pedantic: ^1.8.0

dependency_overrides:
  flattery:
    path: ../webwidgets
